theme: jekyll-theme-minimal
title: Kidney Care Dialysis Center
logo: assets/img/logo.jpeg
description: 
markdown: kramdown
kramdown:
    math_engine: katex
google_analytics: UA-192680612-1

url: "https://kidneycaredialysiscenter.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap